// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package analytics_messaging

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AnalyticsMsgServiceClient is the client API for AnalyticsMsgService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsMsgServiceClient interface {
	SendMessage(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*Response, error)
}

type analyticsMsgServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsMsgServiceClient(cc grpc.ClientConnInterface) AnalyticsMsgServiceClient {
	return &analyticsMsgServiceClient{cc}
}

func (c *analyticsMsgServiceClient) SendMessage(ctx context.Context, in *EventMessage, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/analytics_messaging.AnalyticsMsgService/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsMsgServiceServer is the server API for AnalyticsMsgService service.
// All implementations must embed UnimplementedAnalyticsMsgServiceServer
// for forward compatibility
type AnalyticsMsgServiceServer interface {
	SendMessage(context.Context, *EventMessage) (*Response, error)
	mustEmbedUnimplementedAnalyticsMsgServiceServer()
}

// UnimplementedAnalyticsMsgServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAnalyticsMsgServiceServer struct {
}

func (UnimplementedAnalyticsMsgServiceServer) SendMessage(context.Context, *EventMessage) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (UnimplementedAnalyticsMsgServiceServer) mustEmbedUnimplementedAnalyticsMsgServiceServer() {}

// UnsafeAnalyticsMsgServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsMsgServiceServer will
// result in compilation errors.
type UnsafeAnalyticsMsgServiceServer interface {
	mustEmbedUnimplementedAnalyticsMsgServiceServer()
}

func RegisterAnalyticsMsgServiceServer(s grpc.ServiceRegistrar, srv AnalyticsMsgServiceServer) {
	s.RegisterService(&AnalyticsMsgService_ServiceDesc, srv)
}

func _AnalyticsMsgService_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsMsgServiceServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/analytics_messaging.AnalyticsMsgService/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsMsgServiceServer).SendMessage(ctx, req.(*EventMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsMsgService_ServiceDesc is the grpc.ServiceDesc for AnalyticsMsgService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsMsgService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics_messaging.AnalyticsMsgService",
	HandlerType: (*AnalyticsMsgServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _AnalyticsMsgService_SendMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics_messaging/message_service.proto",
}
